import { useState, useEffect } from 'react';
import { Send, AlertTriangle, ShieldCheck, ShieldAlert, Loader2, MessageCircle, Download, Sparkles, Activity, Search } from 'lucide-react';
import { analyzeMessage, askMentor } from '../services/minimax';
import type { AnalysisResult, ChatMessage } from '../types';

export default function AIChecker() {
  const [messageText, setMessageText] = useState('');
  const [isAnalyzing, setIsAnalyzing] = useState(false);
  const [result, setResult] = useState<AnalysisResult | null>(null);
  const [error, setError] = useState<string | null>(null);

  const [chatMessages, setChatMessages] = useState<ChatMessage[]>([]);
  const [chatInput, setChatInput] = useState('');
  const [isChatting, setIsChatting] = useState(false);
  
  const [scoreWidth, setScoreWidth] = useState(0);

  useEffect(() => {
    if (result) {
      const timer = setTimeout(() => setScoreWidth(result.trustScore), 100);
      return () => clearTimeout(timer);
    } else {
      setScoreWidth(0);
    }
  }, [result]);

  const handleAnalyze = async () => {
    if (!messageText.trim()) return;

    setIsAnalyzing(true);
    setError(null);
    setResult(null);
    setChatMessages([]);
    setScoreWidth(0);

    try {
      const data = await analyzeMessage(messageText);
      setResult(data);
    } catch (err) {
      setError(err instanceof Error ? err.message : 'Analysis failed. Please check your API configuration.');
    } finally {
      setIsAnalyzing(false);
    }
  };

  const handleAskMentor = async (question: string) => {
    if (!question.trim() || !result) return;

    const userMessage: ChatMessage = { role: 'user', content: question };
    setChatMessages((prev) => [...prev, userMessage]);
    setChatInput('');
    setIsChatting(true);

    try {
      const context = `Message analyzed: "${messageText}"\nRisk Level: ${result.riskLevel}\nTechniques: ${result.techniques.join(', ')}`;
      const response = await askMentor(question, context);

      const assistantMessage: ChatMessage = { role: 'assistant', content: response };
      setChatMessages((prev) => [...prev, assistantMessage]);
    } catch (err) {
      const errorMessage: ChatMessage = {
        role: 'assistant',
        content: 'Sorry, I encountered an error. Please try again.',
      };
      setChatMessages((prev) => [...prev, errorMessage]);
    } finally {
      setIsChatting(false);
    }
  };

  const handleExportJSON = () => {
    if (!result) return;
    const data = {
      timestamp: new Date().toISOString(),
      message: messageText,
      analysis: result,
    };
    const json = JSON.stringify(data, null, 2);
    const blob = new Blob([json], { type: 'application/json' });
    const url = URL.createObjectURL(blob);
    const a = document.createElement('a');
    a.href = url;
    a.download = `scam-analysis-${Date.now()}.json`;
    a.click();
    URL.revokeObjectURL(url);
  };

  const handleExportCSV = () => {
    if (!result) return;
    const csv = `Scam Analysis Report
Generated: ${new Date().toLocaleString()}

Analyzed Message:
"${messageText}"

Analysis Results:
Trust Score,${result.trustScore}
Risk Level,${result.riskLevel}
AI-Generated Likelihood,${result.aiLikelihood}

Social Engineering Techniques:
${result.techniques.join('\n')}

Explanation:
${result.explanation}`;

    const blob = new Blob([csv], { type: 'text/csv' });
    const url = URL.createObjectURL(blob);
    const a = document.createElement('a');
    a.href = url;
    a.download = `scam-analysis-${Date.now()}.csv`;
    a.click();
    URL.revokeObjectURL(url);
  };

  const suggestedQuestions = [
    'Why is this considered a scam?',
    'What techniques were used?',
    'Could this be generated by AI?',
  ];

  const getRiskStatus = (score: number) => {
    if (score >= 70) {
      return {
        label: 'Safe',
        styles: 'text-[#22C55E] bg-[#22C55E]/10 border-[#22C55E]/30 shadow-[0_0_15px_rgba(34,197,94,0.2)]',
        barColor: '#22C55E',
        icon: <ShieldCheck className="w-6 h-6" />
      };
    } else if (score > 40) {
      return {
        label: 'Suspicious',
        styles: 'text-[#F59E0B] bg-[#F59E0B]/10 border-[#F59E0B]/30 shadow-[0_0_15px_rgba(245,158,11,0.2)]',
        barColor: '#F59E0B',
        icon: <AlertTriangle className="w-6 h-6" />
      };
    } else {
      return {
        label: 'Scam',
        styles: 'text-[#EF4444] bg-[#EF4444]/10 border-[#EF4444]/30 shadow-[0_0_15px_rgba(239,68,68,0.2)]',
        barColor: '#EF4444',
        icon: <ShieldAlert className="w-6 h-6" />
      };
    }
  };

  const currentRisk = result ? getRiskStatus(result.trustScore) : null;

  return (
    <div className="min-h-screen bg-[#0A0F1E] relative overflow-hidden text-[#E5E7EB]">
      <style>{`
        @keyframes scanline {
          0% { top: -100%; opacity: 0; }
          50% { opacity: 1; }
          100% { top: 200%; opacity: 0; }
        }
        @keyframes fade-in-up {
          0% { opacity: 0; transform: translateY(20px); }
          100% { opacity: 1; transform: translateY(0); }
        }
        .cyber-grid {
          background-size: 40px 40px;
          background-image: 
            linear-gradient(to right, rgba(59, 130, 246, 0.05) 1px, transparent 1px),
            linear-gradient(to bottom, rgba(59, 130, 246, 0.05) 1px, transparent 1px);
        }
        .scan-effect {
          position: absolute;
          left: 0;
          width: 100%;
          height: 100px;
          background: linear-gradient(to bottom, transparent, rgba(59, 130, 246, 0.2), transparent);
          animation: scanline 2.5s linear infinite;
          pointer-events: none;
        }
      `}</style>

      <div className="absolute inset-0 pointer-events-none">
        <div className="absolute inset-0 cyber-grid opacity-30"></div>
        <div className="absolute top-[-10%] right-[-10%] w-[500px] h-[500px] bg-[#3B82F6] rounded-full mix-blend-screen filter blur-[120px] opacity-10 animate-pulse"></div>
        <div className="absolute bottom-[-10%] left-[-10%] w-[500px] h-[500px] bg-[#22D3EE] rounded-full mix-blend-screen filter blur-[120px] opacity-10 animate-pulse delay-700"></div>
      </div>

      <div className="relative z-10 max-w-7xl mx-auto px-4 sm:px-6 lg:px-8 py-12">
        
        <div className="text-center mb-10" style={{ animation: 'fade-in-up 0.6s ease-out' }}>
          <div className="inline-flex items-center justify-center p-3 bg-[#3B82F6]/10 rounded-2xl mb-4 border border-[#3B82F6]/20">
            <Search className="w-8 h-8 text-[#3B82F6]" />
          </div>
          <h1 className="text-4xl md:text-5xl font-bold mb-4">
            AI <span className="text-transparent bg-clip-text bg-gradient-to-r from-[#3B82F6] to-[#22D3EE]">Scam Checker</span>
          </h1>
          <p className="text-lg text-[#9CA3AF] max-w-2xl mx-auto">
            Paste suspicious messages below. Our AI scans for patterns, linguistic triggers, and known social engineering tactics.
          </p>
        </div>

        <div 
          className="bg-[#11172A]/80 backdrop-blur-md border border-[#374151] rounded-3xl p-6 md:p-8 mb-8 shadow-2xl relative overflow-hidden group"
          style={{ animation: 'fade-in-up 0.6s ease-out 0.2s backwards' }}
        >
          <div className="absolute inset-0 border-2 border-transparent group-hover:border-[#3B82F6]/20 rounded-3xl transition-colors pointer-events-none"></div>

          <label className="block text-[#E5E7EB] font-medium mb-3 flex items-center">
            <Activity className="w-4 h-4 mr-2 text-[#22D3EE]" />
            Paste Suspicious Message
          </label>
          
          <textarea
            value={messageText}
            onChange={(e) => setMessageText(e.target.value)}
            placeholder="e.g., 'URGENT: Your account has been compromised. Click here to verify...'"
            className="w-full h-48 bg-[#0A0F1E] border border-[#374151] rounded-xl px-4 py-3 text-[#E5E7EB] placeholder-[#4B5563] focus:outline-none focus:ring-2 focus:ring-[#3B82F6]/50 focus:border-transparent resize-none transition-all"
          />

          <div className="mt-6 flex justify-end">
            <button
              onClick={handleAnalyze}
              disabled={isAnalyzing || !messageText.trim()}
              className="relative overflow-hidden px-8 py-3 bg-gradient-to-r from-[#3B82F6] to-[#22D3EE] text-white font-bold rounded-xl shadow-lg hover:shadow-[#3B82F6]/40 transition-all disabled:opacity-50 disabled:cursor-not-allowed hover:scale-[1.02] active:scale-[0.98]"
            >
              <div className="absolute inset-0 bg-white/20 translate-y-full hover:translate-y-0 transition-transform duration-300"></div>
              <div className="relative flex items-center">
                {isAnalyzing ? (
                  <>
                    <Loader2 className="w-5 h-5 mr-2 animate-spin" />
                    Scanning...
                  </>
                ) : (
                  <>
                    <Sparkles className="w-5 h-5 mr-2" />
                    Analyze with AI
                  </>
                )}
              </div>
            </button>
          </div>
        </div>

        {error && (
          <div className="bg-[#EF4444]/10 border border-[#EF4444]/30 rounded-xl p-4 mb-6 flex items-center animate-pulse">
             <AlertTriangle className="w-5 h-5 text-[#EF4444] mr-3" />
            <p className="text-[#EF4444]">{error}</p>
          </div>
        )}

        {result && currentRisk && (
          <div className="animate-fade-in-up">
            <div className="bg-[#11172A]/80 backdrop-blur-md border border-[#374151] rounded-3xl p-6 md:p-8 mb-8 relative overflow-hidden">
              <div className="scan-effect"></div>

              <div className="flex items-center mb-8 relative z-10">
                <ShieldCheck className="w-6 h-6 text-[#22D3EE] mr-3" />
                <h2 className="text-2xl font-bold text-[#E5E7EB]">Analysis Report</h2>
              </div>

              <div className="grid md:grid-cols-2 gap-6 mb-8 relative z-10">
                <div className="bg-[#0A0F1E] border border-[#374151] rounded-2xl p-6 hover:border-[#3B82F6]/30 transition-colors">
                  <div className="text-[#9CA3AF] text-sm font-medium mb-4">Trust Score</div>
                  <div className="flex items-end mb-4">
                    <span className="text-6xl font-bold text-[#E5E7EB] tracking-tighter">{result.trustScore}</span>
                    <span className="text-2xl text-[#6B7280] ml-2 mb-2">/100</span>
                  </div>
                  <div className="w-full bg-[#1E293B] rounded-full h-3 overflow-hidden">
                    <div
                      className="h-full rounded-full transition-all duration-1000 ease-out shadow-[0_0_10px_currentColor]"
                      style={{
                        width: `${scoreWidth}%`,
                        backgroundColor: currentRisk.barColor,
                        color: currentRisk.barColor
                      }}
                    />
                  </div>
                </div>

                <div className="bg-[#0A0F1E] border border-[#374151] rounded-2xl p-6 hover:border-[#3B82F6]/30 transition-colors flex flex-col justify-center">
                  <div className="text-[#9CA3AF] text-sm font-medium mb-3">Risk Assessment</div>
                  <div
                    className={`inline-flex items-center px-6 py-4 rounded-xl border-2 font-bold text-xl transition-all duration-500 ${currentRisk.styles}`}
                  >
                    {currentRisk.icon}
                    <span className="ml-3 tracking-wide">{currentRisk.label.toUpperCase()}</span>
                  </div>
                </div>
              </div>

              <div className="grid md:grid-cols-3 gap-6 mb-8 relative z-10">
                <div className="bg-[#0A0F1E] border border-[#374151] rounded-2xl p-6 md:col-span-2">
                   <div className="text-[#9CA3AF] text-sm font-medium mb-3">Detected Techniques</div>
                   <div className="flex flex-wrap gap-2">
                    {result.techniques.map((technique, index) => (
                      <span
                        key={index}
                        className="px-3 py-1 bg-[#3B82F6]/10 border border-[#3B82F6]/30 text-[#3B82F6] rounded-lg text-sm font-medium"
                      >
                        {technique}
                      </span>
                    ))}
                  </div>
                </div>

                <div className="bg-[#0A0F1E] border border-[#374151] rounded-2xl p-6">
                   <div className="text-[#9CA3AF] text-sm font-medium mb-2">AI Likelihood</div>
                   <div className="text-2xl font-bold text-[#E5E7EB]">{result.aiLikelihood}</div>
                </div>
              </div>

              <div className="bg-[#0A0F1E] border border-[#374151] rounded-2xl p-6 relative z-10 mb-8">
                <div className="text-[#9CA3AF] text-sm font-medium mb-3">Expert Explanation</div>
                <p className="text-[#E5E7EB] leading-relaxed text-lg">{result.explanation}</p>
              </div>

              <div className="flex flex-wrap gap-3 relative z-10">
                 <button
                  onClick={handleExportJSON}
                  className="flex items-center px-4 py-2 bg-[#1E293B] hover:bg-[#2D3748] text-[#9CA3AF] hover:text-white rounded-lg transition-colors text-sm font-medium border border-[#374151]"
                >
                  <Download className="w-4 h-4 mr-2" />
                  JSON
                </button>
                <button
                  onClick={handleExportCSV}
                  className="flex items-center px-4 py-2 bg-[#1E293B] hover:bg-[#2D3748] text-[#9CA3AF] hover:text-white rounded-lg transition-colors text-sm font-medium border border-[#374151]"
                >
                  <Download className="w-4 h-4 mr-2" />
                  CSV
                </button>
              </div>
            </div>

            <div className="bg-[#11172A]/80 backdrop-blur-md border border-[#374151] rounded-3xl p-6 md:p-8">
              <div className="flex items-center mb-6">
                <MessageCircle className="w-6 h-6 text-[#3B82F6] mr-2" />
                <h2 className="text-2xl font-bold text-[#E5E7EB]">Ask Cyber Mentor</h2>
              </div>

              <div className="mb-6 flex flex-wrap gap-2">
                {suggestedQuestions.map((question, index) => (
                  <button
                    key={index}
                    onClick={() => handleAskMentor(question)}
                    disabled={isChatting}
                    className="px-4 py-2 bg-[#1E293B] border border-[#3B82F6]/30 text-[#3B82F6] hover:bg-[#3B82F6]/10 rounded-full text-sm transition-colors disabled:opacity-50"
                  >
                    {question}
                  </button>
                ))}
              </div>

              <div className="space-y-4 mb-4 max-h-96 overflow-y-auto pr-2 custom-scrollbar">
                {chatMessages.map((msg, index) => (
                  <div
                    key={index}
                    className={`flex ${msg.role === 'user' ? 'justify-end' : 'justify-start'}`}
                  >
                    <div
                      className={`max-w-[85%] p-4 rounded-2xl ${
                        msg.role === 'user'
                          ? 'bg-[#3B82F6] text-white rounded-tr-sm'
                          : 'bg-[#1E293B] border border-[#374151] text-[#E5E7EB] rounded-tl-sm'
                      }`}
                    >
                      <div className="text-xs opacity-70 mb-1 font-bold">
                        {msg.role === 'user' ? 'You' : 'AI Mentor'}
                      </div>
                      <p className="leading-relaxed text-sm">{msg.content}</p>
                    </div>
                  </div>
                ))}
              </div>

              <div className="flex gap-3">
                <input
                  type="text"
                  value={chatInput}
                  onChange={(e) => setChatInput(e.target.value)}
                  onKeyPress={(e) => e.key === 'Enter' && handleAskMentor(chatInput)}
                  placeholder="Ask a follow-up question..."
                  disabled={isChatting}
                  className="flex-1 bg-[#0A0F1E] border border-[#374151] rounded-xl px-4 py-3 text-[#E5E7EB] placeholder-[#4B5563] focus:outline-none focus:ring-2 focus:ring-[#3B82F6]/50 transition-all disabled:opacity-50"
                />
                <button
                  onClick={() => handleAskMentor(chatInput)}
                  disabled={isChatting || !chatInput.trim()}
                  className="px-4 py-3 bg-[#3B82F6] text-white rounded-xl hover:bg-[#2563EB] transition-colors disabled:opacity-50 disabled:cursor-not-allowed shadow-lg hover:shadow-[#3B82F6]/30"
                >
                  {isChatting ? <Loader2 className="w-5 h-5 animate-spin" /> : <Send className="w-5 h-5" />}
                </button>
              </div>
            </div>
          </div>
        )}
      </div>
    </div>
  );
}